#include <stdbool.h>
void showMainMenu();
void clearScreen();
void waitForEnter();
void showSuccessMessage(const char *message);
void showErrorMessage(const char *message);
void showWarningMessage(const char *message);
void showInfoMessage(const char *message);
int getValidatedMenuChoice(int minChoice, int maxChoice);
void showLoadingMessage(const char *action);
void openSummaryMenu(struct MonthReportList *monthReportList);
void openBudgetSettingsMenu(struct MonthReportList *monthReportList);
void openSetCategoryBudgetMenu(struct MonthReportList *monthReportList);
void openViewBudgetMenu(struct MonthReportList *monthReportList);
void openResetBudgetMenu(struct MonthReportList *monthReportList);
void openConfigurationMenu(struct MonthReportList *monthReportList);
void openSetMinimumAmountMenu();
void openSetMinimumBudgetMenu();
void openSetMinimumTransactionMenu();
void openViewConfigurationMenu();
void openResetConfigurationMenu();
void openMainMenu(struct MonthReportList *monthReportList);
void printMainMenuHeader();
void printFiturMenu();
void printInfoUser();
void printFiturMenuRole();
void printMainMenuFooter();
void printBudgetHeader();
int validasiInputBudget();
void handleInputBudget(int choice, struct MonthReportList *monthReportList, bool *shouldExit);
bool hasMonthReports(struct MonthReportList *monthReportList);
void printBudgetCategoryHeader();
struct MonthReport *selectMonthReport(struct MonthReportList *monthReportList);
bool selectCategory(enum TransactionCategory *outCategory);
bool inputNewBudget(long long *outBudget);
void showSetBudgetSuccessMessage(enum TransactionCategory category, long long budget);
bool hasMonthReports(struct MonthReportList *monthReportList);
bool hasMonthReportsView(struct MonthReportList *monthReportList);
void printCurrentBudgetHeader();
struct MonthReport *selectReportForBudgetView(struct MonthReportList *monthReportList);
void printBudgetPerCategoryHeader();
void printBudgetTableRow(const struct TransactionGroup *group);
void printBudgetTableFooter();
void printBudgetReport(const struct MonthReport *report);
void openViewBudgetMenu(struct MonthReportList *monthReportList);
bool ensureHasMonthReports(struct MonthReportList *monthReportList);