#include <stdbool.h>
void showMainMenu();
void clearScreen();
void waitForEnter();
void showSuccessMessage(const char *message);
void showErrorMessage(const char *message);
void showWarningMessage(const char *message);
void showInfoMessage(const char *message);
int getValidatedMenuChoice(int minChoice, int maxChoice);
void showLoadingMessage(const char *action);
void openSummaryMenu(struct MonthReportList *monthReportList);
void openBudgetSettingsMenu(struct MonthReportList *monthReportList);
void openSetCategoryBudgetMenu(struct MonthReportList *monthReportList);
void openViewBudgetMenu(struct MonthReportList *monthReportList);
void openResetBudgetMenu(struct MonthReportList *monthReportList);
void openConfigurationMenu(struct MonthReportList *monthReportList);
void openSetMinimumAmountMenu();
void openSetMinimumBudgetMenu();
void openSetMinimumTransactionMenu();
void openViewConfigurationMenu();
void openResetConfigurationMenu();
void openMainMenu(struct MonthReportList *monthReportList);
void printMainMenuHeader();
void printFiturMenu();
void printInfoUser();
void printFiturMenuRole();
void printMainMenuFooter();
void printBudgetHeader();
int validasiInputBudget();
void handleInputBudget(int choice,struct MonthReportList *monthReportList, bool *shouldExit);